{"name": "test_all_correct_except_invalid_email_data", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'הפרטים נקלטו בהצלחה' == 'נא להזין את האימייל הנכון'\n  - נא להזין את האימייל הנכון\n  + הפרטים נקלטו בהצלחה", "trace": "self = <Web.Tests.test_contactus.TestContactUs object at 0x000002BCBF1B5F60>\n\n    @allure.description(\"Test invalid email\")\n    def test_all_correct_except_invalid_email_data(self):\n        self.handling_the_first_popup()\n        self.click_on_contact_us()\n        self.fill_values_to_first_name_field(self.valid_first_name)\n        self.fill_values_to_last_name_field(self.valid_last_name_)\n        self.fill_values_to_email_field(self.invalid_email)\n        self.fill_values_to_phone_field(self.valid_phone)\n        self.fill_values_to_content_field(self.valid_message)\n        self.click_on_submit()\n>       assert self.verifying_success_message(self.success_message_xpath) == \"נא להזין את האימייל הנכון\"\nE       AssertionError: assert 'הפרטים נקלטו בהצלחה' == 'נא להזין את האימייל הנכון'\nE         - נא להזין את האימייל הנכון\nE         + הפרטים נקלטו בהצלחה\n\nTests\\test_contactus.py:253: AssertionError"}, "description": "Test invalid email", "steps": [{"name": "Opening the qa-trado website", "status": "passed", "start": 1677081714420, "stop": 1677081725084}], "start": 1677081714420, "stop": 1677081728069, "uuid": "215b15cf-0d00-44c1-b87a-edc157d732fe", "historyId": "0d26df5c47316703723bcbcea9f4fd00", "testCaseId": "0b4d5c91b6d1b5972ca31795854a9a81", "fullName": "Tests.test_contactus.TestContactUs#test_all_correct_except_invalid_email_data", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_contactus"}, {"name": "subSuite", "value": "TestContactUs"}, {"name": "host", "value": "mike"}, {"name": "thread", "value": "18868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_contactus"}]}