{"name": "test_all_correct_except_invalid_first_name_data", "status": "failed", "statusDetails": {"message": "AssertionError: assert 'הפרטים נקלטו בהצלחה' == 'נא להזין את השם הפרטי הנכון'\n  - נא להזין את השם הפרטי הנכון\n  + הפרטים נקלטו בהצלחה", "trace": "self = <Web.Tests.test_contactus.TestContactUs object at 0x000002BCBF1B4700>\n\n    @allure.description(\"Test invalid first name\")\n    def test_all_correct_except_invalid_first_name_data(self):\n        self.handling_the_first_popup()\n        self.click_on_contact_us()\n        self.fill_values_to_first_name_field(self.invalid_first_name)\n        self.fill_values_to_last_name_field(self.valid_last_name_)\n        self.fill_values_to_email_field(self.valid_email)\n        self.fill_values_to_phone_field(self.valid_phone)\n        self.fill_values_to_content_field(self.valid_message)\n        self.click_on_submit()\n>       assert self.verifying_success_message(self.success_message_xpath) == \"נא להזין את השם הפרטי הנכון\"\nE       AssertionError: assert 'הפרטים נקלטו בהצלחה' == 'נא להזין את השם הפרטי הנכון'\nE         - נא להזין את השם הפרטי הנכון\nE         + הפרטים נקלטו בהצלחה\n\nTests\\test_contactus.py:227: AssertionError"}, "description": "Test invalid first name", "steps": [{"name": "Opening the qa-trado website", "status": "passed", "start": 1677081683404, "stop": 1677081694023}], "start": 1677081683403, "stop": 1677081697677, "uuid": "b64a6bb1-5628-435e-90c6-3f012230c78b", "historyId": "3b875e9748f58b3f70cf76698b99adf9", "testCaseId": "c0a168b79a9c4dd682cef998b9af03ba", "fullName": "Tests.test_contactus.TestContactUs#test_all_correct_except_invalid_first_name_data", "labels": [{"name": "parentSuite", "value": "Tests"}, {"name": "suite", "value": "test_contactus"}, {"name": "subSuite", "value": "TestContactUs"}, {"name": "host", "value": "mike"}, {"name": "thread", "value": "18868-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Tests.test_contactus"}]}